tar cvzhf \
	Launchbury.tar.gz \
	--transform 's,-Submission-Adequacy,,' \
	Launchbury/Pointwise.thy \
	Launchbury/AList-Utils.thy \
	Launchbury/Nominal-Utils.thy \
	Launchbury/AList-Utils-Nominal.thy \
	Launchbury/Mono-Nat-Fun.thy \
	Launchbury/HOLCF-Utils.thy \
	Launchbury/HOLCF-Meet.thy \
	Launchbury/Nominal-HOLCF.thy \
	Launchbury/Env.thy \
	Launchbury/Env-Nominal.thy \
	Launchbury/Env-HOLCF.thy \
	Launchbury/EvalHeap.thy \
	Launchbury/Vars.thy \
	Launchbury/Terms.thy \
	Launchbury/Substitution.thy \
	Launchbury/Launchbury.thy \
	Launchbury/Value.thy \
	Launchbury/Value-Nominal.thy \
	Launchbury/Iterative.thy \
	Launchbury/HasESem.thy \
	Launchbury/HeapSemantics.thy \
	Launchbury/AbstractDenotational.thy \
	Launchbury/Abstract-Denotational-Props.thy \
	Launchbury/Denotational.thy \
	Launchbury/C.thy \
	Launchbury/C-Meet.thy \
	Launchbury/C-restr.thy \
	Launchbury/CValue.thy \
	Launchbury/CValue-Nominal.thy \
	Launchbury/ResourcedDenotational.thy \
	Launchbury/CorrectnessOriginal.thy \
	Launchbury/CorrectnessResourced.thy \
	Launchbury/ValueSimilarity.thy \
	Launchbury/Denotational-Related.thy \
	Launchbury/ResourcedAdequacy.thy \
	Launchbury/Adequacy.thy \
	Launchbury/EverythingAdequacy.thy \
	Launchbury/document/root_adequacy.tex \
	Launchbury/document/root_adequacy.bib \
	Launchbury/document/map.tex \
	Nominal2-Isabelle2013-1/Nominal/*.ML \
	Nominal2-Isabelle2013-1/Nominal/*.thy \
	Nominal2-Isabelle2013-1-localization.patch \
	ROOT-Submission-Adequacy
